---
- name: Apply  local-path storage
  register: result
  until: result is not failed
  retries: 10
  delay: 10
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/files/local-path-storage.yaml"

- name: Template address pool
  delegate_to: kvm_host_local
  connection: local
  ansible.builtin.template:
    src: metallb-address-pool.yaml.j2
    dest: /tmp/metallb-address-pool.yaml
    mode: "0700"

- name: Apply address pool
  register: result
  until: result is not failed
  retries: 10
  delay: 10
  kubernetes.core.k8s:
    state: present
    src: "/tmp/metallb-address-pool.yaml"

- name: Apply metrics server
  register: result
  until: result is not failed
  retries: 10
  delay: 10
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/files/metrics-server.yaml"

- name: Iclude task Headlamp
  when: options.headlamp
  ansible.builtin.include_tasks:
    file: headlamp.yaml
