---
- name: Start a control plane
  become: true
  with_items:
    - "{{ masters }}"
  community.libvirt.virt:
    name: "{{ item.name }}"
    state: running

- name: Start a worker
  become: true
  with_items:
    - "{{ workers }}"
  community.libvirt.virt:
    name: "{{ item.name }}"
    state: running
