---
- name: Get enabled admission controller plugins
  become: true
  register: result_admission_plugins
  changed_when: false
  ansible.builtin.command: >
    cat /etc/kubernetes/manifests/kube-apiserver.yaml

- name: Set up first control plane
  become: true
  when: admission_plugins | join(',') not in result_admission_plugins.stdout
  changed_when: true
  ansible.builtin.lineinfile:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
    regexp: '^(\s*- --enable-admission-plugins=).*$'
    line: '\1{{ admission_plugins | join(",") }}'
    backrefs: true
