---
- name: Destroy cluster
  become: true
  changed_when: true
  ansible.builtin.command:
    cmd: terraform destroy -auto-approve
    chdir: "{{ playbook_dir }}/.tf"

- name: Remove KVM pool
  become: true
  ansible.builtin.file:
    state: absent
    path: "/var/lib/libvirt/images/{{ cluster_name }}"

- name: Remove .tf directory
  become: true
  ansible.builtin.file:
    state: absent
    path: "{{ playbook_dir }}/.tf"
