---
- name: Destroy terraform
  become: true
  community.general.terraform:
    lock: false
    project_path: "{{ playbook_dir }}/.tf"
    state: absent

- name: Remove KVM pool
  become: true
  ansible.builtin.file:
    state: absent
    path: "/var/lib/libvirt/images/{{ cluster_name }}"

- name: Remove .tf directory
  become: true
  ansible.builtin.file:
    state: absent
    path: "{{ playbook_dir }}/.tf"
