---
- name: Add ingress-nginx repo
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: "https://kubernetes.github.io/ingress-nginx"

- name: Copy values to ansible host
  ansible.builtin.copy:
    src: nginx_values.yaml
    dest: /tmp/nginx_values.yaml
    mode: "0755"

- name: Deploy ingress-nginx controller
  kubernetes.core.helm:
    name: ingress-nginx
    state: present
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    values_files:
      - /tmp/nginx_values.yaml

- name: Remove values file
  ansible.builtin.file:
    path: /tmp/nginx_values.yaml
    state: absent
