---
kvm_host: localhost
image_pool_dir: /var/lib/libvirt/images
network:
  domainName: "{{ cluster_name }}.local"
  ipv4Address: 192.168.1.0
  ipv4_gateway: 192.168.1.1
  ipv4_mask: 255.255.255.192
  lb_address_pool: "192.168.1.30-192.168.1.50"
kubernetes_package_version: 1.30.4-1.1
kubernetes_package_version_splitted: "{{ kubernetes_package_version | split('.') | list }}"
kubernetes_minor_version: >-
  {{
    kubernetes_package_version_splitted[0] + '.' +
    kubernetes_package_version_splitted[1] + '.' +
    (kubernetes_package_version_splitted[2] | split('-') | first)
  }}
kubernetes_major_version: "{{ kubernetes_package_version_splitted[0] }}.{{ kubernetes_package_version_splitted[1] }}"
cni_plugin: flannel
cluster_name: edunetes
timezone: Europe/Helsinki
options:
  headlamp: true
storage_pools:
  - pool:
      name: pool1
      path: /var/lib/libvirt/filesystems/pool1
  - pool:
      name: pool2
      path: /var/lib/libvirt/filesystems/pool2
  - pool:
      name: pool3
      path: /var/lib/libvirt/filesystems/pool3
base_image_checksum: # updated 2023-07-29
  sha256:eca0892c767124069b3b73a85f597d9062ac5dfea49ff09845206db5bc675195
base_image_name: jammy-server-cloudimg-amd64-disk-kvm.img
base_image_url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64-disk-kvm.img
control_planes:
  - disk_size: 30G
    ipv4: 192.168.1.11/26
    name: control-plane
    network_name: virbr-{{ cluster_name }}
    pool_home: /var/lib/libvirt/filesystems/control-plane
    ram_mb: 4096
    vcpus: 2
workers:
  - disk_size: 30G
    ipv4: 192.168.1.21/26
    name: worker01
    network_name: virbr-{{ cluster_name }}
    pool_home: /var/lib/libvirt/filesystems/worker01
    ram_mb: 4096
    vcpus: 2
  - disk_size: 30G
    ipv4: 192.168.1.22/26
    name: worker02
    network_name: virbr-{{ cluster_name }}
    pool_home: /var/lib/libvirt/filesystems/worker02
    ram_mb: 4096
    vcpus: 2
  - disk_size: 30G
    ipv4: 192.168.1.23/26
    name: worker03
    network_name: virbr-{{ cluster_name }}
    pool_home: /var/lib/libvirt/filesystems/worker03
    ram_mb: 4096
    vcpus: 2
