---
kubernetes_package_version: 1.30.3-1.1
kubernetes_package_version_splitted: "{{ version | split('.') | list }}"
kubernetes_version: "{{ kubernetes_package_version_splitted[0] }}.{{ kubernetes_package_version_splitted[1]
  }}.{{ kubernetes_package_version_splitted[2] | split('-') | first }}"
kvm_host: localhost
cluster_name: edunetes
image_pool_dir: /var/lib/libvirt/images
timezone: Europe/Helsinki
network:
  domainName: "{{ cluster_name }}.local"
  ipv4Address: 192.168.1.0
  ipv4_gateway: 192.168.1.1
  ipv4_mask: 255.255.255.192
storage_pools:
  - pool:
      name: pool1
      path: /var/lib/libvirt/filesystems/pool1
  - pool:
      name: pool2
      path: /var/lib/libvirt/filesystems/pool2
  - pool:
      name: pool3
      path: /var/lib/libvirt/filesystems/pool3
base_image_checksum: # updated 2023-08-29
  sha256:cbccd7c4628124278fb427281f33112c60016f3c361c8d5049a68b5411030c04
base_image_name: jammy-server-cloudimg-amd64-disk-kvm.img
base_image_url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64-disk-kvm.img
masters:
  - disk_size: 30G
    ipv4: 192.168.1.11/26
    name: control-plane
    network_name: virbr-{{ cluster_name }}
    pool_home: /var/lib/libvirt/filesystems/control-plane
    ram_mb: 4096
    vcpus: 2
workers:
  - disk_size: 30G
    ipv4: 192.168.1.21/26
    name: worker01
    network_name: virbr-{{ cluster_name }}
    pool_home: /var/lib/libvirt/filesystems/worker01
    ram_mb: 4096
    vcpus: 2
  - disk_size: 30G
    ipv4: 192.168.1.22/26
    name: worker02
    network_name: virbr-{{ cluster_name }}
    pool_home: /var/lib/libvirt/filesystems/worker02
    ram_mb: 4096
    vcpus: 2
  - disk_size: 30G
    ipv4: 192.168.1.23/26
    name: worker03
    network_name: virbr-{{ cluster_name }}
    pool_home: /var/lib/libvirt/filesystems/worker04
    ram_mb: 4096
    vcpus: 2
