---
kvm_host: localhost
image_pool_dir: /var/lib/libvirt/images
network:
  name: virbr-{{ cluster_name }}
  domain_name: "{{ cluster_name }}.local"
  cidr_address: "172.16.254.0/24"
  ipv4Address: 172.16.254.0
  ipv4_gateway: 172.16.254.1
  ipv4_mask: 255.255.255.0
  lb_address_pool: "172.16.254.200-172.16.254.254"
kubernetes_package_version: 1.32.1-1.1
kubernetes_package_version_splitted: "{{ kubernetes_package_version | split('.') | list }}"
kubernetes_minor_version: >-
  {{
    kubernetes_package_version_splitted[0] + '.' +
    kubernetes_package_version_splitted[1] + '.' +
    (kubernetes_package_version_splitted[2] | split('-') | first)
  }}
kubernetes_major_version: "{{ kubernetes_package_version_splitted[0] }}.{{ kubernetes_package_version_splitted[1] }}"
cni_plugin: calico
admission_plugins:
  - NodeRestriction
  - ResourceQuota
cluster_name: edunetes
timezone: Europe/Helsinki
options:
  headlamp:
    enabled: true
    ipv4: 172.16.254.254
  argocd:
    enabled: true
    ipv4: 172.16.254.253
base_image_checksum: # updated 2025-01-29
  sha256:dcc6b52c52e309edbeca2d542c8800a8f9a14f355d71b172cbb83d79ca050d55
base_image_name: jammy-server-cloudimg-amd64.img
base_image_url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
