---
kvm_host: localhost
image_pool_dir: /var/lib/libvirt/images
network:
  name: virbr-{{ cluster_name }}
  domainName: "{{ cluster_name }}.local"
  cidr_address: "192.168.1.1/26"
  ipv4Address: 192.168.1.0
  ipv4_gateway: 192.168.1.1
  ipv4_mask: 255.255.255.192
  lb_address_pool: "192.168.1.30-192.168.1.50"
kubernetes_package_version: 1.30.5-1.1
kubernetes_package_version_splitted: "{{ kubernetes_package_version | split('.') | list }}"
kubernetes_minor_version: >-
  {{
    kubernetes_package_version_splitted[0] + '.' +
    kubernetes_package_version_splitted[1] + '.' +
    (kubernetes_package_version_splitted[2] | split('-') | first)
  }}
kubernetes_major_version: "{{ kubernetes_package_version_splitted[0] }}.{{ kubernetes_package_version_splitted[1] }}"
cni_plugin: flannel
cluster_name: edunetes
timezone: Europe/Helsinki
options:
  headlamp:
    enabled: true
    ipv4: 192.168.1.50
base_image_checksum: # updated 2024-09-14
  sha256:5da0b3d37d02ca6c6760caa4041b4df14e08abc7bc9b2db39133eef8ee145f6d
base_image_name: jammy-server-cloudimg-amd64.img
base_image_url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
