---
cluster_node_set_up_kubernetes_node_packages:
  - curl
  - apt-transport-https
  - vim
  - software-properties-common
  - apt-transport-https
  - ca-certificates
  - python3

cluster_node_set_up_kubernetes_node_kubernetes_packages:
  - kubelet
  - kubeadm
  - kubectl
