---
- name: Fetch cluster config
  become: true
  register: slurpfile
  ansible.builtin.slurp:
    src: /etc/kubernetes/admin.conf

- name: Ensure .kube directory exists
  delegate_to: kvm_host_local
  connection: local
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: "0700"

- name: Create local kubernetes config
  delegate_to: kvm_host_local
  connection: local
  ansible.builtin.copy:
    content: "{{ slurpfile.content | b64decode }}"
    dest: ~/.kube/config
    mode: "0700"

- name: Copy kubeconfig to nodes
  block:

    - name: Include task node_kubeconfig
      with_items: "{{ nodes }}"
      ansible.builtin.include_tasks:
        file: node_kubeconfig.yaml
