---
- name: Check is first control plane responsing
  register: response
  ignore_errors: true
  ansible.builtin.uri:
    url: https://{{ cluster_control_plane_init_first_control_plane.ipv4 | split('/') | first }}:6443
    return_content: true
    validate_certs: false

- name: Set up first control plane
  become: true
  register: result
  when: response.status!=403
  changed_when: true
  ansible.builtin.command:
    cmd:
      kubeadm init
        --kubernetes-version=v"{{ kubernetes_minor_version }}"
        --pod-network-cidr=10.244.0.0/16

- name: Include task kubeconfig
  ansible.builtin.include_tasks:
    file: kubeconfig.yaml

- name: Apply CNI plugin
  delegate_to: kvm_host_local
  connection: local
  changed_when: true
  ansible.builtin.command:
    cmd: >
      /usr/bin/kubectl apply -f {{ playbook_dir }}/files/{{ cni_plugin }}.yaml

- name: Apply Metallb
  delegate_to: kvm_host_local
  connection: local
  changed_when: true
  ansible.builtin.command:
    cmd: >
      /usr/bin/kubectl apply -f {{ playbook_dir }}/files/metallb-native.yaml
