---
- name: Ensure .kube directory exists
  delegate_to: "{{ item.name }}"
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: "0700"

- name: Create local kubernetes config
  delegate_to: "{{ item.name }}"
  ansible.builtin.copy:
    content: "{{ slurpfile.content | b64decode }}"
    dest: ~/.kube/config
    mode: "0700"

- name: Set up kubectl autocompletion
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: "source <(kubectl completion bash)"
    state: present

- name: Set up k alias
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: "alias k=kubectl"
    state: present

- name: Set up k alias autocompletion
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    insertafter: "alias k=kubectl"
    line: "complete -o default -F __start_kubectl k"
    state: present
