---
- name: Open worker ports
  become: true
  notify: Reload UFW
  with_items: "{{ cluster_workers_join_allowed_ports }}"
  community.general.ufw:
    rule: allow
    state: enabled
    port: "{{ item | split('/') | first | string }}"
    proto: "{{ item | split('/') | last | string }}"

# TODO: check is worker already joined

- name: Get join command
  become: true
  delegate_to: "{{ cluster_workers_join_first_control_plane.ipv4 | split('/') | first }}"
  changed_when: true
  register: result
  ansible.builtin.command:
    cmd: >
      kubeadm token create --print-join-command

- name: Set fact join command
  ansible.builtin.set_fact:
    cluster_workers_join_command: /usr/bin/{{ result.stdout }}

- name: Join to the cluster
  become: true
  changed_when: true
  ansible.builtin.command:
    cmd: >
      {{ cluster_workers_join_command }}
