---
- name: Include OS specific KVM packages
  ansible.builtin.include_vars: "{{ ansible_os_family | lower }}.yaml"

- name: Install KVM packages
  become: true
  register: result
  with_items: "{{ kvm_host_set_up_packages }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present

- name: Set swappiness 5
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "5"
  become: true

- name: Define swappiness in sysctl.conf
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/sysctl.conf
    line: vm.swappiness=5
    regexp: ^vm.swappiness
    state: present

- name: Include task rhel9.yaml if distribution Red Hat and version is 9
  ansible.builtin.include_tasks:
    file: rhel9.yaml
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "9"

- name: Include task ubuntu2204.yaml if distribution Ubuntu and version is 22.04
  ansible.builtin.include_tasks:
    file: ubuntu2204.yaml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"

- name: Set kubectl autocompletion
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    state: present
    line: "source <(kubectl completion bash)"

- name: Set up k alias
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: "alias k=kubectl"
    state: present

- name: Set up k alias autocompletion
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    insertafter: "alias k=kubectl"
    line: "complete -o default -F __start_kubectl k"
    state: present
