---
- name: Ensure all nodes in the hosts file
  become: true
  with_items:
    - "{{ nodes }}"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^{{ item.ipv4 }}"
    state: present
    line: "{{ item.ipv4 }} {{ item.name }} {{ item.name }}.{{ cluster_name }}.local"
