---
- name: Install common packages to all nodes
  become: true
  with_items:
    - "{{ set_up_kubernetes_node_packages }}"
  ansible.builtin.package:
    name: "{{ item }}"

- name: Include task hosts file
  with_items:
    - "{{ masters }}"
    - "{{ workers }}"
  ansible.builtin.include_tasks:
    file: hosts_file.yaml

- name: Enable ufw and allow ssh
  become: true
  notify: Reload UFW
  community.general.ufw:
    state: enabled
    rule: allow
    name: OpenSSH

- name: Add overlay and br_netfilter modules
  become: true
  with_items:
    - overlay
    - br_netfilter
  community.general.modprobe:
    name: "{{ item }}"
    state: present

- name: Ensure file /etc/modules-load.d/k8s.conf
  become_user: root
  become: true
  ansible.builtin.file:
    path: /etc/modules-load.d
    state: directory
    mode: '0750'
    owner: root
    group: root

- name: Ensure file /etc/modules-load.d/k8s.conf
  become_user: root
  become: true
  ansible.builtin.file:
    path: /etc/modules-load.d/k8s.conf
    state: touch
    mode: '0750'
    owner: root
    group: root

- name: Ensure overlay in modules k8s.conf
  become: true
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/k8s.conf
    regexp: "^overlay"
    state: present
    line: overlay

- name: Ensure br_netfilter in modules k8s.conf
  become: true
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/k8s.conf
    regexp: "^br_netfilter"
    state: present
    line: br_netfilter

- name: Ensure file /etc/modules-load.d/k8s.conf
  become_user: root
  become: true
  ansible.builtin.file:
    path: /etc/sysctl.d/k8s.conf
    state: touch
    mode: '0750'
    owner: root
    group: root

- name: Ensure net.bridge.bridge-nf-call-iptables in sysctl.d k8s.conf
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/k8s.conf
    regexp: "^net.bridge.bridge-nf-call-iptables"
    state: present
    line: "net.bridge.bridge-nf-call-iptables  = 1"

- name: Ensure net.bridge.bridge-nf-call-ip6tables in sysctl.d k8s.conf
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/k8s.conf
    regexp: "^net.bridge.bridge-nf-call-ip6tables"
    state: present
    line: "net.bridge.bridge-nf-call-ip6tables  = 1"

- name: Ensure net.ipv4.ip_forward in sysctl.d k8s.conf
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/k8s.conf
    regexp: "^net.ipv4.ip_forward"
    state: present
    line: "net.ipv4.ip_forward                 = 1"

- name: Ansible check file exists
  register: key
  ansible.builtin.stat:
    path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Get release key # noqa risky-shell-pipe command-instead-of-module
  become: true
  changed_when: true
  when: "not key.stat.exists"
  ansible.builtin.shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key |
    gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Ansible check file exists
  register: source
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/kubernetes.list

- name: Add repository # noqa risky-shell-pipe command-instead-of-module
  become: true
  changed_when: true
  when: "not source.stat.exists"
  ansible.builtin.shell: |
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' |
    tee /etc/apt/sources.list.d/kubernetes.list

- name: Install kubernetes packages to all nodes
  become: true
  with_items:
    - "{{ set_up_kubernetes_node_kubernetes_packages }}"
  ansible.builtin.apt:
    update_cache: true
    name: "{{ item }}={{ version }}"

- name: Freeze kubernetes packages # noqa command-instead-of-module
  become: true
  with_items:
    - "{{ set_up_kubernetes_node_kubernetes_packages }}"
  changed_when: true
  ansible.builtin.command: >
    apt-mark hold "{{ item }}"

- name: Install containerd package
  become: true
  ansible.builtin.apt:
    name: containerd

- name: Ensure directory /etc/containerd
  become_user: root
  become: true
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0750'
    owner: root
    group: root

- name: Generate containerd config
  ansible.builtin.shell:
    /usr/bin/containerd config default > /home/kubeadmin/config.toml

- name: Copy containerd config file
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: /home/kubeadmin/config.toml
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: "0750"

- name: Configure containerd
  become: true
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: "^            SystemdCgroup = false"
    line: "            SystemdCgroup = true"

- name: Restart containerd service
  become: true
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    daemon_reload: true
    enabled: true

- name: Pull images on host
  become: true
  changed_when: true
  ansible.builtin.command:
    "kubeadm config images pull --kubernetes-version=v{{ set_up_kubernetes_node_version }}"
