---
cluster_control_plane_init_allowed_ports:
  - "6443/tcp"
  - "2379:2380/tcp"
  - "10250/tcp"
  - "10259/tcp"
  - "10257/tcp"

cluster_control_plane_init_first_control_plane: "{{ nodes | selectattr('type', 'equalto', 'control-plane') | first }}"
